services:
  pg-service:
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
      - pg-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-volume: